### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by jerrysiuu** [xxcosmos/buy_pig_plan_python#14]
Traceback (most recent call last):
  File "C:\Users\xiao\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "C:\Users\xiao\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\xiao\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "buy_pig_plan/main.py", line 7, in <module>
    from config import settings
  File "E:\xiao\attack\buy_pig_plan\config.py", line 15, in <module>
    "driver":webdriver.Firefox(),
  File "C:\Users\xiao\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 164, in __init__
    self.service.start()
  File "C:\Users\xiao\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\common\service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

**Comment by likek** [comment]
我也是这样
