### ISSUE TITLE
请问这是什么原因

### ISSUE THREAD

**Issue by isyekong** [xxcosmos/buy_pig_plan_python#2]
系统centos7，drive已安装
`[root@ip-172-26-38-6 buy_pig_plan_python]# python3 main.py
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from config import settings
  File "/home/centos/buy_pig_plan_python/config.py", line 15, in <module>
    "driver":webdriver.Firefox(),
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

`

**Comment by xxcosmos** [comment]
在无 GUI 环境下爬虫，需要安装 firefox 支持，请尝试以下步骤：
```
yum install firefox
yum install Xvfb
yum install libXfont

pip3 install pyvirtualdisplay
```
然后在 main 中 run 方法最前面加入以下代码：
```
from pyvirtualdisplay import Display
display = Display(visible=0, size=(800,600))
display.start()
```
最后面加入
```
display.stop()
```
