### ISSUE TITLE
利用python直接运行出现这个错误，能帮忙看下？

### ISSUE THREAD

**Issue by huanggx** [xxcosmos/buy_pig_plan_python#9]
Traceback (most recent call last):
  File "D:\buy_pig_plan_python-master\main.py", line 62, in <module>
    main()
  File "D:\buy_pig_plan_python-master\main.py", line 19, in main
    url_list = get_url_list()
  File "D:\buy_pig_plan_python-master\main.py", line 57, in get_url_list
    url_list = json.load(f)
  File "C:\Users\hgx\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 39: illegal multibyte sequence

**Comment by Yihsiwei** [comment]
me too

**Comment by zhanyuzhang** [comment]
用脚本批量处理一下name字段，json 里不能出现中文的。

**Comment by Sadcrazy** [comment]
![image](https://github.com/user-attachments/assets/9acdd44f-d59c-45ce-81ef-904fab314348)
基本就是这样错误
